name: Reusable - DB Smoke
on: workflow_call
jobs:
  db:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: pgvector/pgvector:pg16@sha256:c3c84b85691a264aa3c5b8fc1d611e67d42b0cca8596e3d3d22dc2424c12c4e2
        env:
          POSTGRES_USER: journal
          POSTGRES_PASSWORD: journal
          POSTGRES_DB: journal
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U journal" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: astral-sh/setup-uv@208b0c0ee42039b2cbf5fd3ca0ec7d6d8a49336f
      - name: Sync (frozen)
        working-directory: apps/api
        run: uv sync --frozen --all-extras --dev
      - name: Create extensions
        env:
          PGPASSWORD: journal
        run: |
          psql -h localhost -U journal -d journal -c "CREATE EXTENSION IF NOT EXISTS vector;"
          psql -h localhost -U journal -d journal -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
          psql -h localhost -U journal -d journal -c "CREATE EXTENSION IF NOT EXISTS btree_gin;"
      - name: Alembic upgrade
        env:
          DATABASE_URL_SYNC: postgresql+psycopg://journal:journal@localhost:5432/journal
        working-directory: apps/api
        run: uv run alembic -x sqlalchemy.url=${DATABASE_URL_SYNC} upgrade head
      - name: Empty diff check (placeholder)
        run: uv run python ../../scripts/check_empty_diff.py
