name: Reusable - Lint (Python)
on: workflow_call
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ hashFiles('apps/api/uv.lock') }}
      - name: Sync (frozen)
        run: uv sync --frozen
      - name: Ruff format (check)
        run: uv run ruff format --check .
      - name: Ruff check
        run: uv run ruff check .
      - name: Pyright (if configured)
        run: |
          if uv run pyright --version >/dev/null 2>&1; then uv run pyright --warnings; else echo "pyright not configured"; fi

