# Railway Configuration for Journal API
# https://docs.railway.app/reference/config-as-code

[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/Dockerfile"
# Alternative: Use nixpacks (auto-detection)
# builder = "NIXPACKS"
# nixpacksConfigPath = "nixpacks.toml"

[deploy]
# Start command for the API server
startCommand = "cd apps/api && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-5000}"

# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Resource limits
numReplicas = 1
region = "us-west1"

# Environment-specific settings
[environments.production.deploy]
numReplicas = 2
startCommand = "cd apps/api && gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:${PORT:-5000}"

[environments.staging.deploy]
numReplicas = 1
startCommand = "cd apps/api && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-5000} --reload"

# Service definitions for multi-service setup
[[services]]
name = "api"
type = "web"

[[services]]
name = "worker"
type = "worker"
startCommand = "cd apps/api && python -m app.workers.embedding_consumer"

# Static files (if needed)
[static]
enabled = false

# Cron jobs (if needed)
[[crons]]
name = "cleanup"
schedule = "0 3 * * *"  # 3 AM daily
command = "cd apps/api && python -m app.scripts.cleanup"

# Private networking
[experimental]
privateNetworking = true