services:
  scc:
    build:
      context: ..
      dockerfile: .scanner/Dockerfile
    profiles:
      - scan
    network_mode: host
    command: >
      scc --by-file --format json --output .scanner/scc.json .
    volumes:
      - type: bind
        source: ..
        target: /src
        read_only: true
      - type: volume
        source: scanner-data
        target: /.scanner

  merge-results:
    build:
      context: ..
      dockerfile: .scanner/Dockerfile
    profiles:
      - scan
    network_mode: host
    command: >
      python .scanner/scripts/merge_scans.py
    volumes:
      - type: bind
        source: ..
        target: /src
      - type: volume
        source: scanner-data
        target: /.scanner

volumes:
  scanner-data: