#!/usr/bin/env python3
"""
Check that Alembic autogenerate produces an empty diff (no changes).

Runs against the current database (env var DATABASE_URL_SYNC) and writes any
autogenerated revisions to a temp versions directory so the repo is not mutated.
Fails if a revision file is produced.
"""

from __future__ import annotations

import os
import shutil
import sys
import tempfile
from pathlib import Path

from alembic import command
from alembic.config import Config


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    api_dir = repo_root / "apps" / "api"

    db_url = os.getenv(
        "DATABASE_URL_SYNC",
        "postgresql+psycopg://journal:journal@localhost:5432/journal",
    )

    alembic_ini = api_dir / "alembic.ini"
    script_location = api_dir / "alembic"

    if not alembic_ini.exists():
        print(f"[error] alembic.ini not found at {alembic_ini}", file=sys.stderr)
        return 2

    tmp_dir = Path(tempfile.mkdtemp(prefix="alembic-diff-"))
    try:
        versions_dir = tmp_dir / "versions"
        versions_dir.mkdir(parents=True, exist_ok=True)

        cfg = Config(str(alembic_ini))
        cfg.set_main_option("script_location", str(script_location))
        # Use a temp versions directory so we do not touch repo files
        cfg.set_main_option("version_locations", str(versions_dir))
        cfg.set_main_option("sqlalchemy.url", db_url)

        # Generate a revision with autogenerate (no-op if schema is at head)
        try:
            command.revision(cfg, autogenerate=True, message="ci-empty-diff-check")
        except Exception as e:
            # Alembic raises when there are no changes IF the template forbids empty
            # revisions; still verify if any file was created.
            print(f"[info] alembic revision call returned: {e}")

        created = list(versions_dir.glob("*.py"))
        if created:
            print("::error title=Database schema drift detected::Autogenerate produced revision(s):")
            for f in created:
                print(f" - {f}")
            return 1

        print("[ok] Alembic autogenerate produced no revisions (empty diff).")
        return 0
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
