services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: journal
      POSTGRES_PASSWORD: journal
      POSTGRES_DB: journal
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
  nats:
    image: nats:2-alpine
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  postgres_data:
