name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      subset:
        description: "Pytest -k subset (optional)"
        required: false
        default: ""
      verbose:
        description: "Verbose logs"
        required: false
        type: boolean
        default: false

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-test:
    name: Lint, Typecheck, Test
    runs-on: ubuntu-24.04
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun 1.2.21
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.21"

      - name: Web: install, typecheck, build
        working-directory: apps/web
        run: |
          bun install
          bun run quality:types
          bun run build
          node scripts/bundle-check.js

      - name: Install uv 0.8.x
        uses: astral-sh/setup-uv@v4

      - name: API: sync deps
        working-directory: apps/api
        run: uv sync --all-extras --dev

      - name: API: ruff lint
        working-directory: apps/api
        run: uv run ruff check . --output-format=github

      - name: API: ruff format (check)
        working-directory: apps/api
        run: uv run ruff format --check .

      - name: API: mypy
        working-directory: apps/api
        run: uv run mypy app

      # API tests run in dedicated workflows with DB/NATS services
