name: CI

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    name: Web quality + unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.21'
      - name: Install root deps (toolchain)
        run: bun install --frozen-lockfile
      - name: Install deps
        working-directory: apps/web
        run: bun install --frozen-lockfile
      - name: Lint, types, unit, bundle
        run: bun run quality:all
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-vitest-coverage
          path: apps/web/coverage

  api:
    name: API lint + unit/component
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - name: Setup Python
        run: uv python install 3.13
      - name: Sync deps
        run: uv sync --all-extras --dev
      - name: Ruff check
        run: uv run ruff check .
      - name: Ruff format (check)
        run: uv run ruff format --check .
      - name: Mypy
        run: uv run mypy app
      - name: Pytest unit+component
        run: uv run pytest -m "unit or component" -v
