name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-test:
    name: Lint, Typecheck, Test
    runs-on: ubuntu-latest
    env:
      OTEL_ENABLED: "false"
      LOG_LEVEL: INFO
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun 1.2.21
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.21"

      - name: Bun version
        run: bun --version

      - name: Install JS deps
        run: bun install --frozen-lockfile

      - name: Install web app deps
        run: bun --cwd apps/web install --frozen-lockfile

      - name: Build and publish web bundle
        run: bun run web:publish

      - name: Verify Vite manifest exists
        run: |
          test -f journal/static/gen/web/manifest.json || (echo "Missing Vite manifest" && exit 1)

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install uv 0.8.x
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          uv --version

      - name: Set up Python 3.13.7 via uv
        run: |
          uv python install 3.13.7
          uv python pin 3.13.7

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Sync Python deps (frozen)
        run: uv sync --frozen

      - name: Biome CI (GitHub reporter)
        run: bun run check

      - name: TypeScript typecheck
        run: bun run typecheck

      - name: Ruff Lint (GitHub annotations)
        run: uv run ruff check . --output-format=github

      - name: Ruff Format (check only)
        run: uv run ruff format --check .

      - name: Mypy
        run: uv run mypy .

      - name: Pytest with coverage (fail under 80%)
        run: uv run pytest --cov=journal --cov-report=xml --cov-fail-under=80

      - name: Playwright a11y tests
        run: bun run test:a11y

      - name: Playwright visual tests
        run: bun run test:visual

      - name: Build Storybook static
        run: bun run build-storybook

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static
          if-no-files-found: warn

      - name: Upload Playwright report (if available)
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: warn
