name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      subset:
        description: "Pytest -k subset (optional)"
        required: false
        default: ""
      verbose:
        description: "Verbose logs"
        required: false
        type: boolean
        default: false

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

env:
  PYTHON_VERSION: "3.13"
  UV_CACHE_DIR: /tmp/.uv-cache
  INFISICAL_CLI_REQUIRED: "false"  # CI jobs don't need Infisical CLI

jobs:
  build-test:
    name: Lint, Typecheck, Test
    runs-on: ubuntu-24.04
    env:
      CI: true
    steps:
      - name: Checkout exact SHA
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup Bun 1.2.21
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.21"

      - name: Web: install, typecheck, build
        working-directory: apps/web
        run: |
          bun install
          bun run quality:types
          bun run build
          node scripts/bundle-check.js

      - name: Install uv 0.8.x
        uses: astral-sh/setup-uv@v4

      - name: API: sync deps
        working-directory: apps/api
        run: uv sync --all-extras --dev

      # Diagnostic: Show what CI sees
      - name: Show HEAD and diff summary
        run: |
          git rev-parse HEAD
          git --no-pager show --name-status --oneline -n 1

      - name: Confirm offending lines exist (key files)
        working-directory: apps/api
        run: |
          echo "---- key_manager.py imports ----"
          nl -ba app/domain/auth/key_manager.py | sed -n '1,20p'
          echo "---- rate_limiter.py imports ----"
          nl -ba app/domain/auth/rate_limiter.py | sed -n '1,20p'
          echo "---- jwks_metrics.py around 90-110 ----"
          nl -ba app/telemetry/jwks_metrics.py | sed -n '90,110p'
          echo "---- FakeAsyncSession around 88-100 ----"
          nl -ba tests/security/conftest.py | sed -n '88,100p'

      - name: Print Ruff version & settings
        working-directory: apps/api
        run: |
          uv run ruff --version
          uv run ruff config

      - name: API: ruff lint (no cache)
        working-directory: apps/api
        run: |
          rm -rf .ruff_cache
          uv run ruff check . --no-cache --force-exclude --output-format=github

      - name: API: ruff format (check)
        working-directory: apps/api
        run: uv run ruff format --check .

      - name: API: mypy (no cache)
        working-directory: apps/api
        run: |
          rm -rf .mypy_cache
          uv run mypy app

      # Guards to prevent re-introduction of fixed issues
      - name: Guard: no bare type: ignore
        working-directory: apps/api
        run: |
          ! rg -n "# type: ignore(?!\[)" || (echo "::error title=Bare type ignore found::Use specific codes like [arg-type] or [override]" && exit 1)

      - name: Guard: no unused asyncio imports
        working-directory: apps/api
        run: |
          ! rg -n "^import asyncio$" app/domain/auth/{key_manager,rate_limiter}.py || (echo "::error title=Unused asyncio import::Use built-in TimeoutError instead" && exit 1)

      # API tests run in dedicated workflows with DB/NATS services
