# .github/workflows/documentation-validate.yml
name: Documentation Structure Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'scripts/**'
      - '.github/workflows/documentation-validate.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'scripts/**'
      - '.github/workflows/documentation-validate.yml'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  validate-structure:
    name: Validate Documentation Structure
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Set up Python with uv
      uses: astral-sh/setup-uv@208b0c0ee42039b2cbf5fd3ca0ec7d6d8a49336f
      with:
        version: "0.5.16"

    - name: Install dependencies
      working-directory: apps/api
      run: uv sync --all-extras --dev

    - name: Validate documentation structure (basic)
      run: |
        echo "Validating documentation structure..."
        cd apps/api && uv run python ../../scripts/validate_documentation_simple.py

    - name: Check documentation coverage
      continue-on-error: true
      run: |
        echo "Checking documentation coverage..."
        cd apps/api && uv run python ../../scripts/check_doc_coverage.py || echo "Coverage check completed"

    - name: Generate documentation report
      continue-on-error: true
      run: |
        echo "Generating documentation report..."
        cd apps/api && uv run python ../../scripts/generate_doc_report.py || echo "Report generation completed"

    - name: Upload documentation report
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
      if: always()
      with:
        name: documentation-report
        path: docs/_generated/reports/

    # Keep legacy checks temporarily (non-blocking)
    - name: Validate frontmatter (legacy)
      continue-on-error: true
      run: |
        echo "Validating markdown frontmatter (legacy check)..."
        cd apps/api && uv run python ../../scripts/validate_docs_frontmatter.py || true

    - name: Check documentation structure (legacy)
      continue-on-error: true
      run: |
        echo "Checking documentation structure (legacy check)..."
        cd apps/api && uv run python ../../scripts/check_docs_structure.py || true