# .github/workflows/documentation-validate.yml
name: Documentation Structure Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/documentation-validate.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/documentation-validate.yml'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  validate-structure:
    name: Validate Documentation Structure
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Validate frontmatter
      run: |
        echo "Validating markdown frontmatter..."
        python scripts/validate_docs_frontmatter.py
    
    - name: Check documentation structure
      run: |
        echo "Checking documentation structure..."
        python scripts/check_docs_structure.py