# .github/workflows/frontend-build.yml
name: Frontend Build

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/src/**'
      - 'apps/web/vite.config.ts'
      - 'apps/web/package.json'
      - 'apps/web/bun.lock'
      - '.github/workflows/frontend-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/src/**'
      - 'apps/web/vite.config.ts'
      - 'apps/web/package.json'
      - 'apps/web/bun.lock'
      - '.github/workflows/frontend-build.yml'
  workflow_dispatch: {}

jobs:
  build:
    name: Build Frontend Assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: '1.2.21'
    - name: Install & Build
      working-directory: apps/web
      run: |
        bun install
        bun run build
    - name: Upload built assets
      uses: actions/upload-artifact@v4
      with:
        name: web-dist
        path: apps/web/dist
        if-no-files-found: error
