# .github/workflows/frontend-build.yml
name: Frontend Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - '.github/workflows/frontend-build.yml'

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.21'
      - name: Install deps
        working-directory: apps/web
        run: bun install --frozen-lockfile
      - name: Build
        working-directory: apps/web
        run: bun run build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist
          if-no-files-found: error
