# .github/workflows/python-tests.yml
name: Python Tests (api via uv)

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/python-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/python-tests.yml'

jobs:
  test:
    name: API Lint/Type
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v4
      - name: Sync deps
        run: uv sync --all-extras --dev
      - name: Ruff
        run: uv run ruff check . --output-format=github
      - name: Mypy
        run: uv run mypy .
      # No pytest here; tests run in api-tests.yml with required services
