# .github/workflows/python-tests.yml
name: Python Tests (api via uv)

# DISABLED: Duplicate of ci.yml which also runs Ruff and mypy
# This was causing stale cache/ref issues where one workflow
# would see old code while the other saw new code.
# Keep ci.yml as the single source of truth for linting.
on:
  workflow_dispatch:  # Only manual trigger for now
    inputs:
      note:
        description: "This duplicates ci.yml; use that instead"
        required: false
        default: ""

jobs:
  test:
    name: API Lint/Type
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup uv
        uses: astral-sh/setup-uv@e779db74266a80753577425b0e4e3b6b2e7f4f6a
      - name: Sync deps
        run: uv sync --all-extras --dev
      - name: Ruff
        run: uv run ruff check . --output-format=github
      - name: Mypy
        run: uv run mypy .
      # No pytest here; tests run in api-tests.yml with required services
