# .github/workflows/python-tests.yml
name: Python Tests (API)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/python-tests.yml'

jobs:
  api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - name: Setup Python
        run: uv python install 3.13
      - name: Sync deps
        run: uv sync --all-extras --dev
      - name: Pytest (unit+component)
        run: uv run pytest -m "unit or component" -v
