# Verify Python 3.13 and Ruff 0.13.0 Alignment
name: Verify Alignment
on: [push, pull_request]

jobs:
  verify-alignment:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.13'

      - uses: astral-sh/setup-uv@208b0c0ee42039b2cbf5fd3ca0ec7d6d8a49336f
        with:
          version: "latest"

      - name: Python and Ruff versions
        run: |
          python3 --version | tee python-version.txt
          # Pin Ruff to 0.13.0 for alignment
          uvx ruff==0.13.0 --version | tee ruff-version.txt

          # Verify Python 3.13
          grep -q "^Python 3\.13\." python-version.txt || (echo "❌ Not Python 3.13"; exit 1)
          echo "✅ Python 3.13 verified"

          # Verify Ruff 0.13.0
          grep -q "^ruff 0\.13\.0" ruff-version.txt || (echo "❌ Not Ruff 0.13.0"; exit 1)
          echo "✅ Ruff 0.13.0 verified"

      - name: Effective Ruff config
        working-directory: apps/api
        run: |
          # Use the pinned Ruff version for config introspection
          uvx ruff==0.13.0 check . --show-settings 2>&1 | tee ../../ruff-config.txt

          # Must show preview = true and explicit-preview-rules = true
          grep -q 'linter.preview = enabled' ../../ruff-config.txt || (echo "❌ Ruff preview off"; exit 1)
          grep -q 'linter.explicit_preview_rules = true' ../../ruff-config.txt || (echo "❌ explicit-preview-rules off"; exit 1)
          echo "✅ Ruff configuration verified"

      - name: Stale reference scan
        run: |
          echo "Checking for stale Python versions..."
          if git grep -nE "(python|Python)( |:|-)?3\.(11|12)\b" -- \
            ":!**/site-packages/**" ":!**/node_modules/**" ":!*.lock" \
            ":!docs/RUFF_*.md" ":!docs/adr/adr-0001-python-3.13-ruff-0.13.md" ":!package-lock.json" \
            ":!docs.backup.*/**" ":!**/.backups/**" ":!scripts/**"; then
            echo "❌ Found stale Python version references"
            exit 1
          fi
          echo "✅ No stale Python version references"

          echo "Checking for actual legacy tool usage (not Ruff config)..."
          # Look for actual imports/installs of legacy tools, not Ruff config sections
          if git grep -nE "(^import (isort|flake8|black)|^from (isort|flake8|black)|pip install.*(isort|flake8|black))" -- \
            ":!**/site-packages/**" ":!**/vendor/**" ":!**/third_party/**" \
            ":!**/node_modules/**" ":!*.lock" ":!**/RUFF_*.md" ":!**/.pre-commit-config.yaml" \
            ":!.github/workflows/verify-alignment.yml" ":!apps/api/.devcontainer/**" \
            ":!docs/guides/**" ":!docs/initial-planning/**" \
            ":!docs.backup.*/**" ":!scripts/**"; then
            echo "❌ Found actual legacy tool usage"
            exit 1
          fi
          echo "✅ No legacy tool usage detected"

          # Check for redundant tool blocks (actual config sections, not Ruff subsections)
          if git grep -nE '^\[tool\.(black|isort|flake8)\]' -- "*.toml"; then
            echo "❌ Found redundant tool blocks in pyproject.toml"
            exit 1
          fi
          echo "✅ No redundant tool blocks"

      - name: Lint + Format checks
        working-directory: apps/api
        run: |
          uvx ruff==0.13.0 clean
          uvx ruff==0.13.0 check . --output-format=github
          uvx ruff==0.13.0 format --check .
          echo "✅ All linting and formatting checks pass"

      - name: Docker Python version check
        run: |
          # Check Dockerfiles
          for dockerfile in $(find . -name "Dockerfile*" -type f -not -path "*/node_modules/*"); do
            if grep -q "FROM.*python" "$dockerfile"; then
              if ! grep -q "python:3.13" "$dockerfile"; then
                echo "❌ $dockerfile not using Python 3.13"
                exit 1
              fi
            fi
          done
          echo "✅ All Dockerfiles use Python 3.13"

      - name: Docs drift check
        run: |
          # TODO: After merging to main, ensure ripgrep regex patterns work correctly
          # Currently using simplified grep due to CI environment issues
          # This should be revisited to use proper regex validation
          if [ -f "./scripts/validate-docs.sh" ]; then
            ./scripts/validate-docs.sh
          else
            echo "⚠️ validate-docs.sh not found, skipping docs check"
          fi

      - name: Generate alignment report
        if: always()
        run: |
          echo "# Python 3.13 & Ruff 0.13.0 Alignment Report" > alignment-report.txt
          echo "Generated: $(date)" >> alignment-report.txt
          echo "" >> alignment-report.txt

          if [ -f python-version.txt ]; then
            echo "## Python Version" >> alignment-report.txt
            cat python-version.txt >> alignment-report.txt
            echo "" >> alignment-report.txt
          fi

          if [ -f ruff-version.txt ]; then
            echo "## Ruff Version" >> alignment-report.txt
            cat ruff-version.txt >> alignment-report.txt
            echo "" >> alignment-report.txt
          fi

          if [ -f ruff-config.txt ]; then
            echo "## Ruff Configuration (excerpt)" >> alignment-report.txt
            grep -E "preview|explicit" ruff-config.txt | head -10 >> alignment-report.txt
            echo "" >> alignment-report.txt
          fi

          echo "## Validation Results" >> alignment-report.txt
          echo "See workflow run for detailed results" >> alignment-report.txt

      - name: Upload alignment report
        if: always()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: alignment-report
          path: |
            alignment-report.txt
            ruff-config.txt
            python-version.txt
            ruff-version.txt
